server:
  port: 8080

debug: false

#logging:
#  level:
#    org.zhangxiao.paladin2: debug
#    org.springframework.web: debug

#paladin2:
#  swagger2:
#    can-visit: true # 默认为false
#  admin:
#    jwt-secret: 安全起见，建议设置
#    password-salt: 安全起见，建议设置
  
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/paladin2?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.cnvp.hd.entity
  global-config:
    db-config:
      db-type: mysql
      field-strategy: not_null
      id-type: auto
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    #配置JdbcTypeForNull
#    jdbc-type-for-null: 'null'